### ISSUE TITLE
$ testrpc -g 30000000000 -l 200000000 命令中-g -l的作用是什么？

### ISSUE THREAD

**Issue by Huaida** [Guigulive/Team-F#64]
testrpc 默认启动，部署合约时提示gas不够。
$ testrpc -g 30000000000 -l 200000000
需要重设，-g -l 分别表示gas 和 gaslimit，请问gas 和gaslimit 的作用分别是什么？

**Comment by zchcai** [comment]
From [testrpc](https://github.com/trufflesuite/ganache-cli)
gasLimit: Maximum amount of gas available to each block and transaction. 
gasPrice: THe price of each unit of gas.
